[openweathermap]
enabled = true
api_key = "f7384f28dec7db208b36e69ccd295958"
city_id = "4671654"
notification_timeout = 10
notification_body = "Expected within the next 3 hours"
sync_frequency = 600
display = "{{ temp_icon }} {{ temp_fahrenheit }}°F {{ trend }} {{ forecast_icon }} {{ forecast_fahrenheit }}°F"

[mpd]
enabled = true
music_directory = "/home/nicholas/Music/Sorted"
notification_timeout = 10
cover_name = "cover.jpg"
skip_missing_cover = true

# GitHub configuration
[github]
# Enable / disable GitHub integration
enabled = false
# Go to https://github.com/settings/tokens
# Click on "Generate a new token", give it a name and check the "notifications" checkbox
# Use one of the following forms to set your token:
# api_key = "file:~/your_folder/some-token.txt"   # Read from a file
# api_key = "env:GITHUB_TOKEN"                    # Read from an environment variable
# api_key = "PLAINTEXT_VALUE"                     # Read the value directly
api_key = "file:~/.config/ntfd/github.txt"
# How long GitHub notifications should stay up (in seconds)
notification_timeout = 20
# Whether or not the organization/owner avatar should be shown in the notification
show_avatar = true
# How often should we fetch from the GitHub API (in seconds)
# Will default to 10 seconds for values under 10 seconds
sync_frequency = 30
# Output format, using Handlebars syntax, meaning variables should be used like {{ this }}
# Available tokens are:
# - unread_count
# - first_time_count
display = " {{ unread_count }}"

