# TODO: create second segment for non-command indicator

# typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|terraform'

typeset -g POWERLEVEL9K_AWS_CLASSES=(
  '*spadash*' PROD
  'default' DEFAULT
  '*'       OTHER)

typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=208
typeset -g POWERLEVEL9K_AWS_DEFAULT_VISUAL_IDENTIFIER_EXPANSION=' '
typeset -g POWERLEVEL9K_AWS_DEFAULT_CONTENT_EXPANSION=''

typeset -g POWERLEVEL9K_AWS_OTHER_FOREGROUND=62
typeset -g POWERLEVEL9K_AWS_OTHER_VISUAL_IDENTIFIER_EXPANSION=' '
typeset -g POWERLEVEL9K_AWS_OTHER_CONTENT_EXPANSION='${P9K_CONTENT}'

# typeset -g POWERLEVEL9K_AWS_PROD_FOREGROUND=160
typeset -g POWERLEVEL9K_AWS_PROD_BACKGROUND=52
typeset -g POWERLEVEL9K_AWS_PROD_FOREGROUND=230
typeset -g POWERLEVEL9K_AWS_PROD_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_AWS_PROD_CONTENT_EXPANSION='${P9K_CONTENT}'
