
###############################################################
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
# - set special behaviors on specific paths
#
# Configuration documentation is available at
#     https://dystroy.org/broot
###############################################################

###############################################################
# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`)
# A popular flag is the `g` one which displays git related info.
#
default_flags = "sdgh"

###############################################################
# Special paths
# If some paths must be handled specially, uncomment (and change
# this section as per the examples
#
# [special-paths]
# "/mnt" = "no-enter"
# "/home/nicholas/Music" = "no-enter"

###############################################################
# Date/Time format
# If you want to change the format for date/time, uncomment the
# following line and change it according to
# https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html
#
# date_time_format = "%Y/%m/%d %R"
date_time_format = "%m-%d %R"

###############################################################
# Whether to mark the selected line with a triangle
#
# show_selection_mark = true

###############################################################
# Column order
# cols_order, if specified, must be a permutation of "gbpdscn"
# where every char denotes a column:
#  g : Git file info
#  b : branch (shows the depth and parent in the tree)
#  p : permissions (mode, user, group)
#  d : last modification date
#  s : size (with size bar when sorting)
#  c : count, number of files in directories
#  n : file name
#
# cols_order = "gscPdbn"

###############################################################
# True Colors
# If this parameter isn't set, broot tries to automatically
# determine whether true colors (24 bits) are available.
# As this process is unreliable, you may uncomment this setting
# and set it to false or true if you notice the colors in
# previewed images are too off.
true_colors = true
syntax_theme = "Solarized (dark)"

# base16-ocean.dark
# base16-eighties.dark
# base16-mocha.dark
# base16-ocean.light
# InspiredGitHub
# Solarized (dark)
# Solarized (light)

###############################################################
# Verbs and shortcuts
# You can define your own commands which would be applied to
# the selection.
#
# Exemple 1: launching `tail -n` on the selected file (leaving broot)
# [[verbs]]
# name = "tail_lines"
# invocation = "tl {lines_count}"
# execution = "tail -f -n {lines_count} {file}"
#
# Exemple 2: creating a new file without leaving broot
# [[verbs]]
# name = "touch"
# invocation = "touch {new_file}"
# execution = "touch {directory}/{new_file}"
# leave_broot = false


[[verbs]]
invocation = "root"
key = "ctrl-R"
execution = ":focus /"

[[verbs]]
invocation = "projects"
shortcut = "p"
key = "alt-P"
execution = ":focus ~/projects"

[[verbs]]
invocation = "root"
key = "alt-R"
execution = ":focus /"

[[verbs]]
invocation = "home"
key = "alt-H"
execution = ":focus ~"

[[verbs]]
name = "panel_left"
key = "alt-left"
execution = ":panel_left"

[[verbs]]
name = "panel_right"
key = "alt-right"
execution = ":panel_right"

[[verbs]]
name = "toggle_preview"
key = "alt-/"
execution = ":toggle_preview"

[[verbs]]
name = "toggle_preview"
key = "ctrl-v"
execution = ":toggle_preview"

[[verbs]]
invocation = "edit"
shortcut = "e"
execution = "$EDITOR +{line} {file}"
leave_broot = false

[[verbs]]
key = "enter"
execution = "$EDITOR +{line} {file}"
leave_broot = false
apply_to = "file"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"
leave_broot = false

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
leave_broot = false
execution = "git difftool -y {file}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"
leave_broot = false

[[verbs]]
name = "toggle_preview"
key = "F3"
shortcut = "tv"
invocation = "preview"
execution = ":toggle_preview"

[[verbs]]
name = "toggle_dates"
shortcut = "td"
invocation = "dates"
execution = ":toggle_dates"

[[verbs]]
name = "toggle_perm"
shortcut = "tp"
invocation = "perm"
execution = ":toggle_perm"

[[verbs]]
name = "toggle_counts"
shortcut = "tc"
invocation = "count"
execution = ":toggle_counts"

[[verbs]]
name = "toggle_sizes"
shortcut = "ts"
invocation = "sizes"
execution = ":toggle_sizes"

[[verbs]]
name = "toggle_gitstatus"
invocation="gitstatus"
key = "ctrl-g"
shortcut = "tgs"
execution = ":toggle_git_status"

[[verbs]]
name = "toggle_gitignore"
invocation = "gitigniore"
shortcut = "tgi"
execution = ":toggle_git_ignore"

[[verbs]]
name = "sort_dates"
shortcut = "sd"
invocation = "sortdate"
execution = ":sort_by_date"

[[verbs]]
name = "sort_counts"
shortcut = "sc"
invocation = "sortcount"
execution = ":sort_by_count"

[[verbs]]
name = "sort_sizes"
shortcut = "ss"
invocation = "sortsize"
execution = ":sort_by_size"

[[verbs]]
key = "home"
execution = ":select_first"

[[verbs]]
key = "end"
execution = ":select_last"

[[verbs]]
name = "line_down"
key = "ctrl-n"
execution = ":line_down"

[[verbs]]
name = "line_up"
key = "ctrl-p"
execution = ":line_up"

[[verbs]]
key = "ctrl-f"
execution = ":page_down"

[[verbs]]
key = "ctrl-b"
execution = ":page_up"

[[verbs]]
key = "ctrl-["
execution = ":back"
#
# You can reproduce the bindings of Norton Commander
# on copying or moving to the other panel:
#
# [[verbs]]
# key = "F5"
# execution = ":copy_to_panel"
#
# [[verbs]]
# key = "F6"
# execution = ":move_to_panel"


###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.
[skin]
#
# default = "gray(23) none / gray(20) none"
# tree = "ansi(94) None / gray(3) None"
# file = "gray(20) None / gray(15) None"
# directory = "ansi(208) None Bold / ansi(172) None bold"
# exe = "Cyan None"
# link = "Magenta None"
# pruning = "gray(12) None Italic"
# perm__ = "gray(5) None"
# perm_r = "ansi(94) None"
# perm_w = "ansi(132) None"
# perm_x = "ansi(65) None"
# owner = "ansi(138) None"
# group = "ansi(131) None"
# count = "ansi(136) gray(3)"
# dates = "ansi(66) None"
# sparse = "ansi(214) None"
# content_extract = "ansi(29) None"
# content_match = "ansi(34) None"
# git_branch = "ansi(229) None"
# git_insertions = "ansi(28) None"
# git_deletions = "ansi(160) None"
# git_status_current = "gray(5) None"
# git_status_modified = "ansi(28) None"
# git_status_new = "ansi(94) None Bold"
# git_status_ignored = "gray(17) None"
# git_status_conflicted = "ansi(88) None"
# git_status_other = "ansi(88) None"
# selected_line = "None gray(5) / None gray(4)"
# char_match = "Yellow None"
# file_error = "Red None"
# flag_label = "gray(15) None"
# flag_value = "ansi(208) None Bold"
# input = "White None / gray(15) gray(2)"
# status_error = "gray(22) ansi(124)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) gray(3) / gray(2) gray(2)"
# status_italic = "ansi(208) gray(3) / gray(2) gray(2)"
# status_bold = "ansi(208) gray(3) Bold / gray(2) gray(2)"
# status_code = "ansi(229) gray(3) / gray(2) gray(2)"
# status_ellipsis = "gray(19) gray(1) / gray(2) gray(2)"
# purpose_normal = "gray(20) gray(2)"
# purpose_italic = "ansi(178) gray(2)"
# purpose_bold = "ansi(178) gray(2) Bold"
# purpose_ellipsis = "gray(20) gray(2)"
# scrollbar_track = "gray(7) None / gray(4) None"
# scrollbar_thumb = "gray(22) None / gray(14) None"
# help_paragraph = "gray(20) None"
# help_bold = "ansi(208) None Bold"
# help_italic = "ansi(166) None"
# help_code = "gray(21) gray(3)"
# help_headers = "ansi(208) None"
# help_table_border = "ansi(239) None"
# preview = "gray(20) gray(1) / gray(18) gray(2)"
# preview_line_number = "gray(12) gray(3)"
# preview_match = "None ansi(29)"
# hex_null = "gray(11) None"
# hex_ascii_graphic = "gray(18) None"
# hex_ascii_whitespace = "ansi(143) None"
# hex_ascii_other = "ansi(215) None"
# hex_non_ascii = "ansi(167) None"
#
# [skin] (orange)
# tree = "ansi(94) None / gray(3) None"
# file = "gray(20) None / gray(15) None"
# directory = "ansi(208) None Bold / ansi(172) None bold"
# exe = "Cyan None"
# link = "Magenta None"
# pruning = "gray(12) None Italic"
# perm__ = "gray(5) None"
# perm_r = "ansi(94) None"
# perm_w = "ansi(132) None"
# perm_x = "ansi(65) None"
# owner = "ansi(138) None"
# group = "ansi(131) None"
# count = "ansi(136) gray(3)"
# dates = "ansi(66) None"
# sparse = "ansi(214) None"
# content_extract = "ansi(29) None"
# content_match = "ansi(34) None"
# git_branch = "ansi(229) None"
# git_insertions = "ansi(28) None"
# git_deletions = "ansi(160) None"
# git_status_current = "gray(5) None"
# git_status_modified = "ansi(28) None"
# git_status_new = "ansi(94) None Bold"
# git_status_ignored = "gray(17) None"
# git_status_conflicted = "ansi(88) None"
# git_status_other = "ansi(88) None"
# selected_line = "None gray(5) / None gray(4)"
# char_match = "Yellow None"
# file_error = "Red None"
# flag_label = "gray(15) None"
# flag_value = "ansi(208) None Bold"
# input = "White None / gray(15) gray(2)"
# status_error = "gray(22) ansi(124)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) gray(3) / gray(2) gray(2)"
# status_italic = "ansi(208) gray(3) / gray(2) gray(2)"
# status_bold = "ansi(208) gray(3) Bold / gray(2) gray(2)"
# status_code = "ansi(229) gray(3) / gray(2) gray(2)"
# status_ellipsis = "gray(19) gray(1) / gray(2) gray(2)"
# purpose_normal = "gray(20) gray(2)"
# purpose_italic = "ansi(178) gray(2)"
# purpose_bold = "ansi(178) gray(2) Bold"
# purpose_ellipsis = "gray(20) gray(2)"
# scrollbar_track = "gray(7) None / gray(4) None"
# scrollbar_thumb = "gray(22) None / gray(14) None"
# help_paragraph = "gray(20) None"
# help_bold = "ansi(208) None Bold"
# help_italic = "ansi(166) None"
# help_code = "gray(21) gray(3)"
# help_headers = "ansi(208) None"
# help_table_border = "ansi(239) None"
# preview = "gray(20) gray(1) / gray(18) gray(2)"
# preview_line_number = "gray(12) gray(3)"
# preview_match = "None ansi(29) Underlined"
# hex_null = "gray(10) None"
# hex_ascii_graphic = "gray(18) None"
# hex_ascii_whitespace = "ansi(143) None"
# hex_ascii_other = "ansi(215) None"
# hex_non_ascii = "ansi(167) None"
#
# [skin]
default = "rgb(131, 148, 150) rgb(0, 8, 12) / rgb(131, 148, 150) rgb(0, 18, 25)"  # base0 base03 / base01 base02
preview = "none gray(0) / none gray(1)"
preview_line_number = "gray(12) gray(1)"
file = "none none"                                                                 # default default
link = "rgb(108, 143, 196) none"
owner = "rgb(88, 110, 117) none"                                                   # base01 default
group = "rgb(88, 110, 117) none"                                                   # base01 default
#
# tree = "rgb(88, 110, 117) none"                                                    # base01 default
# file = "none none"                                                                 # default default
# directory = "rgb(38, 139, 210) none bold"                                          # blue default bold
# exe = "rgb(211, 1, 2) none"                                                        # red default
# link = "rgb(211, 54, 130) none"                                                    # magenta default
# pruning = "rgb(88, 110, 117) none italic"                                          # base01 default italic
# perm__ = "rgb(88, 110, 117) none"                                                  # base01 default
# perm_r = "none none"                                                               # default default
# perm_w = "none none"                                                               # default default
# perm_x = "none none"                                                               # default default
# owner = "rgb(88, 110, 117) none"                                                   # base01 default
# group = "rgb(88, 110, 117) none"                                                   # base01 default
# sparse = "none none"                                                               # default default
# git_branch = "rgb(147, 161, 161) none"                                             # base1 default
# git_insertions = "rgb(133, 153, 0) none"                                           # green default
# git_deletions = "rgb(211, 1, 2) none"                                              # red default
# git_status_current = "none none"                                                   # default default
# git_status_modified = "rgb(181, 137, 0) none"                                      # yellow default
# git_status_new = "rgb(133, 153, 0) none"                                           # green default
# git_status_ignored = "rgb(88, 110, 117) none"                                      # base01 default
# git_status_conflicted = "rgb(211, 1, 2) none"                                      # red default
# git_status_other = "rgb(211, 1, 2) none"                                           # red default
# selected_line = "none rgb(7, 54, 66)"                                              # default base02
# char_match = "rgb(133, 153, 0) none underlined"                                    # green default underlined
# file_error = "rgb(203, 75, 22) none italic"                                        # orange default italic
# flag_label = "none none"                                                           # default default
# flag_value = "rgb(181, 137, 0) none bold"                                          # yellow default bold
# input = "none none"                                                                # default default
# status_error = "rgb(203, 75, 22) rgb(7, 54, 66)"                                   # orange base02
# status_job = "rgb(108, 113, 196) rgb(7, 54, 66) bold"                              # violet base02 bold
# status_normal = "none rgb(7, 54, 66)"                                              # default base02
# status_italic = "rgb(181, 137, 0) rgb(7, 54, 66)"                                  # yellow base02
# status_bold = "rgb(147, 161, 161) rgb(7, 54, 66) bold"                             # base1 base02 bold
# status_code = "rgb(108, 113, 196) rgb(7, 54, 66)"                                  # violet base02
# status_ellipsis = "none rgb(7, 54, 66)"                                            # default base02
# scrollbar_track = "rgb(7, 54, 66) none"                                            # base02 default
# scrollbar_thumb = "none none"                                                      # default default
# help_paragraph = "none none"                                                       # default default
# help_bold = "rgb(147, 161, 161) none bold"                                         # base1 default bold
# help_italic = "rgb(147, 161, 161) none italic"                                     # base1 default italic
# help_code = "rgb(147, 161, 161) rgb(7, 54, 66)"                                    # base1 base02
# help_headers = "rgb(181, 137, 0) none"                                             # yellow default
# help_table_border = "none none"                                                    # default default

###############################################################
# File Extension Colors
#
# uncomment and modify the next section if you want to color
# file name depending on their extension
#

[ext-colors]
# png = "rgb(255, 128, 75)"
# rs = "yellow"

