vim.cmd("colorscheme nord")
vim.cmd('hi! Normal guibg=NONE ctermbg=NONE')
vim.cmd('hi! EndOfBuffer guibg=NONE ctermbg=NONE')
vim.cmd('hi! SignColumn guibg=NONE ctermbg=NONE')

vim.cmd('hi! String guifg=#22BB99 ctermfg=green')
vim.cmd('hi Normal guifg=#9a9aaa ctermfg=white')
vim.cmd('hi! LineNr guibg=NONE ctermbg=NONE')
vim.cmd('hi! CursorLine guibg=#182224 ctermfg=Black')
vim.cmd('hi! CursorLineNr guifg=#afd7ff ctermfg=Black')
vim.cmd('hi! CursorColumn guibg=NONE ctermbg=NONE')
vim.cmd('hi! Comment gui=italic')

vim.cmd('hi! LspDiagnosticsDefaultWarning guifg=#664400')
vim.cmd('hi! LspDiagnosticsDefaultError guifg=#990000')
vim.cmd('hi! LspDiagnosticsDefaultHint guifg=#666688')
vim.cmd('hi! LspDiagnosticsDefaultInformation guifg=#664466')
