version: '3.7'

services:
  server:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        GIT_USER_NAME: [YOUR_FULL_NAME]
        GIT_USER_EMAIL: [YOUR_EMAIL]
    environment:
      UID:
      GID:
