-- require "../colorschemes/jellybeans"
-- require "../colorschemes/blue-moon"
-- require "../colorschemes/boo"
-- require "../colorschemes/gruvbox"
-- require "../colorschemes/material"
-- require "../colorschemes/moonlight"
-- require "../colorschemes/neg"
-- require "../colorschemes/neon"
-- require "../colorschemes/nightfly"
-- require "../colorschemes/nord-vim"
-- require "../colorschemes/nord-nick"
-- require "../colorschemes/nord-lush"
-- require "../colorschemes/nord-nvim"
-- require "../colorschemes/nvcode"
-- require("lush_theme.jellybeans-nvim")
-- local spec = require("colorschemes.nord-nvim")
-- require("lush")(spec)
